service:
  name: serverless-cap-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  
custom:
  topicName: imagesTopic-Todo-${self:provider.stage}
  serverless-offline:
    httpPort: 8080
    useChildProcesses: true

  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    stages:
      - ${self:provider.stage}

  documentation:
    api:
      info:
        version: v1.0.0
        title: Serverless cap
        description: Serverless application for creating todos
    models:
      - name: CreateTodoRequest
        contentType: application/json
        schema: ${file(src/requests/schema/create-todo.json)}
      - name: UpdateTodoRequest
        contentType: application/json
        schema: ${file(src/requests/schema/update-todo.json)}    

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
        
  environment:
    AUTH0_JSON_KEY_URL: https://dev-1nt0v2c1.auth0.com/.well-known/jwks.json
    TODOS_TABLE: Cap-Todo-${self:provider.stage}
    TODO_INDEX_NAME: TodoIdIndex
    CONNECTIONS_TABLE: Connections-Todo-${self:provider.stage}
    # IMAGES_TABLE: Images-${self:provider.stage}
    # IMAGE_ID_INDEX: ImageIdIndex
    TODOS_S3_BUCKET: serverless-cap-bucket-5hv3az69bh-${self:provider.stage}
    # IMAGES_S3_BUCKET: serverless-udagram-images-aa15o72a-${self:provider.stage}
    THUMBNAILS_S3_BUCKET: serverless-cap-thumbnail-5hv3az69bh-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300

functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:274225709315:table/${self:provider.environment.TODOS_TABLE}

  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          cors: true
          authorizer: Auth
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new todo
            description: Create a new todo
            requestModels:
              'application/json': CreateTodoRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:274225709315:table/${self:provider.environment.TODOS_TABLE}

  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}
          cors: true
          authorizer: Auth
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Update todo
            description: Update todo
            requestModels:
              'application/json': UpdateTodoRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:274225709315:table/${self:provider.environment.TODOS_TABLE}

  DeleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:274225709315:table/${self:provider.environment.TODOS_TABLE}

  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:PutObject
        Resource: 'arn:aws:s3:::${self:provider.environment.TODOS_S3_BUCKET}/*'
      - Effect: "Allow"
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:274225709315:table/${self:provider.environment.TODOS_TABLE}
        
  SendUploadNotifications:
    environment:
      STAGE: ${self:provider.stage}
      API_ID:
        Ref: WebsocketsApi
    handler: src/lambda/s3/sendNotifications.handler
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - arn:aws:sns
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - ${self:custom.topicName}
          topicName: ${self:custom.topicName}

  # ResizeImage:
  #   handler: src/lambda/s3/resizeImage.handler
  #   events:
  #     - sns:
  #         arn:
  #           Fn::Join:
  #             - ':'
  #             - - arn:aws:sns
  #               - Ref: AWS::Region
  #               - Ref: AWS::AccountId
  #               - ${self:custom.topicName}
  #         topicName: ${self:custom.topicName}

  ConnectHandler:
    handler: src/lambda/websocket/connect.handler
    events:
      - websocket:
          route: $connect
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:274225709315:table/${self:provider.environment.CONNECTIONS_TABLE}

  DisconnectHandler:
    handler: src/lambda/websocket/disconnect.handler
    events:
      - websocket:
          route: $disconnect
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:274225709315:table/${self:provider.environment.CONNECTIONS_TABLE}      
      
resources:
  - ${file(./resources/dynamo_db.yml)}
  - ${file(./resources/api_gateway.yml)}
  - ${file(./resources/s3.yml)}